import './globals.css'
import { Satoshi, TTCommons } from '../util/font'
import { createGlobalStyle } from 'styled-components'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html className={`${Satoshi.variable} ${TTCommons.variable}`} lang="ja">
      <body>{children}</body>
    </html>
  )
}

